/orbslam2/orbslam2_driver:
  ros__parameters:
    autostart: true
    body_frame_id: base_footprint
    camera_orientation_topic: '/imu_plugin/out'
    camera_topic_1: /seppia/zed2i_left_camera/image_raw
    camera_topic_2: /seppia/zed2i_right_camera/image_raw
    covariance_scaling_factor: 1.0
    display: true
    frame_view: false
    global_frame_id: ''
    link_namespace: 'seppia/'
    mode: STEREO
    preconvert_frames: true
    publish_map: true
    publish_tf: true
    orb2_config_path: /home/neo/workspace/src/ORB-SLAM2/src/ORB-SLAM2/Config/Stereo-ZED2i-VGA.yaml
    save_map: false
    set_gravity_as_origin: true
    start_localization: false
    subscriber_depth: 30
    tracking_cpu: -1
    transport: raw
    use_sim_time: false
    verbose: false
    vocabulary_path: /home/neo/workspace/src/ORB-SLAM2/src/ORB-SLAM2/Vocabulary/orb_mur.fbow
